// Generated by Anvil.
// https://github.com/square/anvil
@file:Suppress(
  "DEPRECATION",
  "OPT_IN_USAGE",
  "OPT_IN_USAGE_ERROR",
)

package com.fret.gallery_list.impl

import com.fret.gallery_list.impl.viewmodels.GalleryListViewModel
import com.fret.utils.ViewModelFactory
import com.fret.utils.ViewModelFactoryExperimental
import dagger.assisted.AssistedFactory
import kotlin.String
import kotlin.Suppress

//@AssistedFactory
//interface GalleryListViewModelAssistedFactory :
//    GalleryListViewModelFactory {
//}
