// Generated by Anvil.
// https://github.com/square/anvil
@file:Suppress(
  "DEPRECATION",
  "OPT_IN_USAGE",
  "OPT_IN_USAGE_ERROR",
)

package com.fret.gallery_list.impl

import kotlin.Suppress

//@AssistedFactory
//interface GalleryListViewModelAssistedFactory :
//    GalleryListViewModelFactory {
//}
